version: "2"
services:
  code-server:
    build: ./code-server
    container_name: code-server
    network_mode: host
    privileged: true
    environment:
      - PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - DOCKER_MODS=linuxserver/mods:code-server-zsh|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-nvm|linuxserver/mods:universal-docker-in-docker
      - SHELL=/usr/bin/zsh
    volumes:
      - "code-server:/config"
    restart: unless-stopped
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-socket: 1
  photos:
    image: bh.cr/balenalabs/photo-gallery-aarch64/0.0.4 # where <arch> is one of aarch64, armv7hf, rpi or amd64 and <version>(optional) is a specific version of this block
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    restart: always
    ports:
      - "8888"
volumes:
  code-server:
